### ISSUE TITLE
How to get new access token after it expires?

### ISSUE THREAD

**Issue by anhkhoi** [isikom/nodemailer-smtp-gmail-example#1]
Hey guys, nothing codes to handle when access token expires?

**Comment by zauker** [comment]
Hi @anhkhoi I only updated Nodemailer to latest version and it works fine.

If want try it, you have to not set the access token in createTransport options so it will be created using the refresh token.

es.
```
"transport": {
    "host": "smtp.gmail.com",
    "port": 465,
    "secure": true,
    "auth": {
      "type": "OAuth2",
      "user": "user@example.com",
      "clientId": "000000000000-xxx0.apps.googleusercontent.com",
      "clientSecret": "XxxxxXXxX0xxxxxxxx0XXxX0",
      "refreshToken": "1/XXxXxsss-xxxXXXXXxXxx0XXXxxXXx0x00xxx",
      "accessToken": ""
    }
  }
```

I added a simple function:
```
transporter.on('token', token => {
    console.log('A new access token was generated');
    console.log('User: %s', token.user);
    console.log('Access Token: %s', token.accessToken);
    console.log('Expires: %s', new Date(token.expires));
});
```
You can see the log of new access token generated.

If you want, you can enable debug log adding the options `"logger": true` and `"debug": true` to logs SMTP traffic.

**Comment by anhkhoi** [comment]
`
[2019-05-17 04:48:34] ERROR Send Error: invalid_grant
{ Error: invalid_grant
    at postRequest (/Users/khoitran/workspace/nodemailer-smtp-gmail-example/node_modules/nodemailer/lib/xoauth2/index.js:259:33)
    at PassThrough.req.once (/Users/khoitran/workspace/nodemailer-smtp-gmail-example/node_modules/nodemailer/lib/xoauth2/index.js:328:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) code: 'EAUTH', command: 'AUTH XOAUTH2' }
`

`the email wasn't sent.`

Thank for reply @zauker, I used my credential and let access token empty but I still got error "invalid grant"
I am using node v8.12.0
