### ISSUE TITLE
error "invalid grant"

### ISSUE THREAD

**Issue by zauker** [isikom/nodemailer-smtp-gmail-example#2]
`
[2019-05-17 04:48:34] ERROR Send Error: invalid_grant
{ Error: invalid_grant
    at postRequest (/Users/khoitran/workspace/nodemailer-smtp-gmail-example/node_modules/nodemailer/lib/xoauth2/index.js:259:33)
    at PassThrough.req.once (/Users/khoitran/workspace/nodemailer-smtp-gmail-example/node_modules/nodemailer/lib/xoauth2/index.js:328:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at PassThrough.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9) code: 'EAUTH', command: 'AUTH XOAUTH2' }
`

`the email wasn't sent.`

Thank for reply @zauker, I used my credential and let access token empty but I still got error "invalid grant"
I am using node v8.12.0

_Originally posted by @anhkhoi in https://github.com/isikom/nodemailer-smtp-gmail-example/issues/1#issuecomment-493318951_

**Comment by zauker** [comment]
Hi @anhkhoi, concerning your issues it seems you did set the right scope in [Google OAuth 2.0 Playground](https://developers.google.com/oauthplayground/).

 
![Schermata 2019-05-17 alle 12 09 46](https://user-images.githubusercontent.com/932680/57921183-13dd9c80-789d-11e9-84b9-73e707ceed6a.png)

**Comment by anhkhoi** [comment]
Thank bro @zauker, it works for me. I forgot to enter the client id/client secret on google playground setting. Thank for your support.
